package com.perp.sasregistmodel.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 08 14:05:51 ICT 2010
// ---------------------------------------------------------------------
public interface AccountsRow extends Row {
    Number getAccId();

    void setAccId(Number value);

    String getFullName();

    void setFullName(String value);

    String getContactTelephone();

    void setContactTelephone(String value);

    String getEmail();

    void setEmail(String value);

    String getOrganizationName();

    void setOrganizationName(String value);

    Number getProId();

    void setProId(Number value);

    String getAddress();

    void setAddress(String value);

    String getTaxCode();

    void setTaxCode(String value);

    Number getRolId();

    void setRolId(Number value);

    Number getNumberOfEmployee();

    void setNumberOfEmployee(Number value);

    String getCustomerApproach();

    void setCustomerApproach(String value);

    String getUserName();

    void setUserName(String value);

    String getPassword();

    void setPassword(String value);

    String getActivedCode();

    void setActivedCode(String value);

    Number getCouId();

    void setCouId(Number value);

    Number getIndId();

    void setIndId(Number value);

    String getStatus();

    void setStatus(String value);

    Number getSquId();

    void setSquId(Number value);

    String getSecurityAnswer();

    void setSecurityAnswer(String value);

    Number getMmeId();

    void setMmeId(Number value);

    Number getLabId();

    void setLabId(Number value);

    String getActivatedFlag();

    void setActivatedFlag(String value);

    void setIsAdmin(String value);

    String getIsAdmin();
}
