package com.perp.sasregistmodel.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 14 11:48:11 ICT 2014
// ---------------------------------------------------------------------
public interface LoginHistoriesViewRow extends Row {
    void setUserName(String value);

    void setUserAgent(String value);

    void setPlatform(String value);

    void setModule(String value);

    void setLogoutAt(Date value);

    void setLoginAt(Date value);

    void setLhiId(Number value);

    void setIpAddress(String value);

    void setEnvId(String value);

    void setCountry(String value);

    void setAttribute5(String value);

    void setAttribute4(String value);

    void setAttribute3(String value);

    void setAttribute2(String value);

    void setAttribute1(String value);

    String getUserName();

    String getUserAgent();

    String getPlatform();

    String getModule();

    Date getLogoutAt();

    Date getLoginAt();

    Number getLhiId();

    String getIpAddress();

    String getEnvId();

    String getCountry();

    String getAttribute5();

    String getAttribute4();

    String getAttribute3();

    String getAttribute2();

    String getAttribute1();

    void setStatus(String value);

    String getStatus();

    void setAccId(Number value);

    Number getAccId();
}
