package com.vc.sasnmodel.views.customize.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 15 09:31:59 ICT 2010
// ---------------------------------------------------------------------
public interface C01DocumentDownloadsRow extends Row {
    Number getDdoId();

    void setDdoId(Number value);

    Number getDcaId();

    void setDcaId(Number value);

    String getTitle();

    void setTitle(String value);

    String getShortContent();

    void setShortContent(String value);

    Date getPublicDate();

    void setPublicDate(Date value);

    String getDownloadLink();

    void setDownloadLink(String value);

    BlobDomain getDownloadData();

    void setDownloadData(BlobDomain value);

    Number getDataSize();

    void setDataSize(Number value);

    Number getDownloadCount();

    void setDownloadCount(Number value);

    Number getPriorityOrder();

    void setPriorityOrder(Number value);

    String getFileName();

    void setFileName(String value);

    String getFileType();

    void setFileType(String value);
}
