package com.vc.sasnmodel.views.customize.common;

import oracle.jbo.Row;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 22 22:22:30 ICT 2010
// ---------------------------------------------------------------------
public interface C01NewsOthersRow extends Row {
    Number getNotId();

    void setNotId(Number value);

    String getNotNumber();

    void setNotNumber(String value);

    String getTitle();

    void setTitle(String value);

    ClobDomain getContent();

    void setContent(ClobDomain value);

    String getDescription();

    void setDescription(String value);
}
