package com.perp.sasregistmodel.views.sasr002.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 14:17:37 ICT 2009
// ---------------------------------------------------------------------
public interface Sasr002A2SubscriptionsRow extends Row {
    Number getAccId();

    void setAccId(Number value);

    String getActivatedCode();

    void setActivatedCode(String value);

    String getAppUrl();

    void setAppUrl(String value);

    Date getEndDate();

    void setEndDate(Date value);

    Number getQuantity();

    void setQuantity(Number value);

    Number getSpaId();

    void setSpaId(Number value);

    Date getStartDate();

    void setStartDate(Date value);

    String getStatus();

    void setStatus(String value);

    Number getSubId();

    void setSubId(Number value);

    Date getSubscribeDate();

    void setSubscribeDate(Date value);
}
