package com.perp.sasenvmodel.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 03 10:58:29 ICT 2009
// ---------------------------------------------------------------------
public interface PerpSasEnvAppModule extends ApplicationModule {
  void test();

  ViewObject getSasem001Environments();

  int getCountSubscriptionExceptEnvId(Long envId, Long subId);
}
