package com.perp.sasmodel.views.sas;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 27 16:12:13 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppUsersRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AppName {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAppName();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAppName((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AusId {
            public Object get(AppUsersRowImpl obj) {
                return obj.getAusId();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setAusId((Number)value);
            }
        }
        ,
        ChartAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getChartAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setChartAdmin((String)value);
            }
        }
        ,
        CreateDate {
            public Object get(AppUsersRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(AppUsersRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        EmpId {
            public Object get(AppUsersRowImpl obj) {
                return obj.getEmpId();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setEmpId((String)value);
            }
        }
        ,
        ForumAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getForumAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setForumAdmin((String)value);
            }
        }
        ,
        KiAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getKiAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setKiAdmin((String)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(AppUsersRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ModifyDate {
            public Object get(AppUsersRowImpl obj) {
                return obj.getModifyDate();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setModifyDate((Date)value);
            }
        }
        ,
        Password {
            public Object get(AppUsersRowImpl obj) {
                return obj.getPassword();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setPassword((String)value);
            }
        }
        ,
        ProAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getProAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setProAdmin((String)value);
            }
        }
        ,
        Status {
            public Object get(AppUsersRowImpl obj) {
                return obj.getStatus();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        StoInCceAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getStoInCceAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setStoInCceAdmin((String)value);
            }
        }
        ,
        TimecheckAdmin {
            public Object get(AppUsersRowImpl obj) {
                return obj.getTimecheckAdmin();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setTimecheckAdmin((String)value);
            }
        }
        ,
        UserName {
            public Object get(AppUsersRowImpl obj) {
                return obj.getUserName();
            }

            public void put(AppUsersRowImpl obj, Object value) {
                obj.setUserName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AppUsersRowImpl object);

        public abstract void put(AppUsersRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPNAME = AttributesEnum.AppName.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int AUSID = AttributesEnum.AusId.index();
    public static final int CHARTADMIN = AttributesEnum.ChartAdmin.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int FORUMADMIN = AttributesEnum.ForumAdmin.index();
    public static final int KIADMIN = AttributesEnum.KiAdmin.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFYDATE = AttributesEnum.ModifyDate.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int PROADMIN = AttributesEnum.ProAdmin.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STOINCCEADMIN = AttributesEnum.StoInCceAdmin.index();
    public static final int TIMECHECKADMIN = AttributesEnum.TimecheckAdmin.index();
    public static final int USERNAME = AttributesEnum.UserName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AppUsersRowImpl() {
    }

    /**
     * Gets AppUsers entity object.
     * @return the AppUsers
     */
    public EntityImpl getAppUsers() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for APP_NAME using the alias name AppName.
     * @return the APP_NAME
     */
    public String getAppName() {
        return (String) getAttributeInternal(APPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_NAME using the alias name AppName.
     * @param value value to set the APP_NAME
     */
    public void setAppName(String value) {
        setAttributeInternal(APPNAME, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for AUS_ID using the alias name AusId.
     * @return the AUS_ID
     */
    public Number getAusId() {
        return (Number) getAttributeInternal(AUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for AUS_ID using the alias name AusId.
     * @param value value to set the AUS_ID
     */
    public void setAusId(Number value) {
        setAttributeInternal(AUSID, value);
    }

    /**
     * Gets the attribute value for CHART_ADMIN using the alias name ChartAdmin.
     * @return the CHART_ADMIN
     */
    public String getChartAdmin() {
        return (String) getAttributeInternal(CHARTADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for CHART_ADMIN using the alias name ChartAdmin.
     * @param value value to set the CHART_ADMIN
     */
    public void setChartAdmin(String value) {
        setAttributeInternal(CHARTADMIN, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for EMP_ID using the alias name EmpId.
     * @return the EMP_ID
     */
    public String getEmpId() {
        return (String) getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ID using the alias name EmpId.
     * @param value value to set the EMP_ID
     */
    public void setEmpId(String value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for FORUM_ADMIN using the alias name ForumAdmin.
     * @return the FORUM_ADMIN
     */
    public String getForumAdmin() {
        return (String) getAttributeInternal(FORUMADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for FORUM_ADMIN using the alias name ForumAdmin.
     * @param value value to set the FORUM_ADMIN
     */
    public void setForumAdmin(String value) {
        setAttributeInternal(FORUMADMIN, value);
    }

    /**
     * Gets the attribute value for KI_ADMIN using the alias name KiAdmin.
     * @return the KI_ADMIN
     */
    public String getKiAdmin() {
        return (String) getAttributeInternal(KIADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for KI_ADMIN using the alias name KiAdmin.
     * @param value value to set the KI_ADMIN
     */
    public void setKiAdmin(String value) {
        setAttributeInternal(KIADMIN, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @return the MODIFY_DATE
     */
    public Date getModifyDate() {
        return (Date) getAttributeInternal(MODIFYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @param value value to set the MODIFY_DATE
     */
    public void setModifyDate(Date value) {
        setAttributeInternal(MODIFYDATE, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for PRO_ADMIN using the alias name ProAdmin.
     * @return the PRO_ADMIN
     */
    public String getProAdmin() {
        return (String) getAttributeInternal(PROADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for PRO_ADMIN using the alias name ProAdmin.
     * @param value value to set the PRO_ADMIN
     */
    public void setProAdmin(String value) {
        setAttributeInternal(PROADMIN, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for STO_IN_CCE_ADMIN using the alias name StoInCceAdmin.
     * @return the STO_IN_CCE_ADMIN
     */
    public String getStoInCceAdmin() {
        return (String) getAttributeInternal(STOINCCEADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for STO_IN_CCE_ADMIN using the alias name StoInCceAdmin.
     * @param value value to set the STO_IN_CCE_ADMIN
     */
    public void setStoInCceAdmin(String value) {
        setAttributeInternal(STOINCCEADMIN, value);
    }

    /**
     * Gets the attribute value for TIMECHECK_ADMIN using the alias name TimecheckAdmin.
     * @return the TIMECHECK_ADMIN
     */
    public String getTimecheckAdmin() {
        return (String) getAttributeInternal(TIMECHECKADMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for TIMECHECK_ADMIN using the alias name TimecheckAdmin.
     * @param value value to set the TIMECHECK_ADMIN
     */
    public void setTimecheckAdmin(String value) {
        setAttributeInternal(TIMECHECKADMIN, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
