package com.perp.sasmodel.views.sas;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 19 08:45:23 GMT+07:00 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SasEmployeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SasEmployeesImpl() {
    }
}
