package com.perp.sasmodel.common;


import com.perp.beans.PerpAccountChecking;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 25 12:51:02 ICT 2009
// ---------------------------------------------------------------------
public interface PerpSasAppModule extends ApplicationModule {
    PerpAccountChecking doPerpAccountChecking(String userName, String password,
                                              String captchaText);

    PerpAccountChecking doPerpSasLogin(String userName, String password,
                                       String captchaText,
                                       String subscriptionCode);

    void prepareToShowSasMenusSearch(String appCode, Long ausId,
                                     String searchText, String findIn);

    void prepareToShowSasUserRoles(String appCode, Long ausId);

    void prepareToShowAdv02OrganizationUnitsP01(Number ounId);

    void createAppLogin(String userName, String envId, String browser,
                        Date loginAt, String ipAddress, String country);


    void prepareToShowAppLogins();
    
    void prepareToShowDiagramProcesses(String appCode);
    
    boolean doChangePassword(Long ausId, String newPassword);

}
