package com.vc.sasnmodel.views.customize.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 22 22:22:30 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class C01NewsOthersRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public C01NewsOthersRowClient() {
    }

    public Number getNotId() {
        return (Number)getAttribute("NotId");
    }

    public void setNotId(Number value) {
        setAttribute("NotId", value);
    }

    public String getNotNumber() {
        return (String)getAttribute("NotNumber");
    }

    public void setNotNumber(String value) {
        setAttribute("NotNumber", value);
    }

    public String getTitle() {
        return (String)getAttribute("Title");
    }

    public void setTitle(String value) {
        setAttribute("Title", value);
    }

    public ClobDomain getContent() {
        return (ClobDomain)getAttribute("Content");
    }

    public void setContent(ClobDomain value) {
        setAttribute("Content", value);
    }

    public String getDescription() {
        return (String)getAttribute("Description");
    }

    public void setDescription(String value) {
        setAttribute("Description", value);
    }
}
