package com.perp.sasmodel.client;


import com.perp.beans.PerpAccountChecking;
import com.perp.sasmodel.common.PerpSasAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 25 12:51:02 ICT 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerpSasAppModuleClient extends ApplicationModuleImpl implements PerpSasAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public PerpSasAppModuleClient() {
    }


    public PerpAccountChecking doPerpAccountChecking(String userName,
                                                     String password,
                                                     String captchaText) {
        Object _ret =
            this.riInvokeExportedMethod(this, "doPerpAccountChecking",
                                        new String[] { "java.lang.String",
                                                       "java.lang.String",
                                                       "java.lang.String" },
                                        new Object[] { userName, password,
                                                       captchaText });
        return (PerpAccountChecking)_ret;
    }

    public PerpAccountChecking doPerpSasLogin(String userName, String password,
                                              String captchaText,
                                              String subscriptionCode) {
        Object _ret =
            this.riInvokeExportedMethod(this, "doPerpSasLogin", new String[] { "java.lang.String",
                                                                               "java.lang.String",
                                                                               "java.lang.String",
                                                                               "java.lang.String" },
                                        new Object[] { userName, password,
                                                       captchaText,
                                                       subscriptionCode });
        return (PerpAccountChecking)_ret;
    }

    public void prepareToShowSasMenusSearch(String appCode, Long ausId,
                                            String searchText, String findIn) {
        Object _ret =
            this.riInvokeExportedMethod(this, "prepareToShowSasMenusSearch",
                                        new String[] { "java.lang.String",
                                                       "java.lang.Long",
                                                       "java.lang.String",
                                                       "java.lang.String" },
                                        new Object[] { appCode, ausId,
                                                       searchText, findIn });
        return;
    }

    public void prepareToShowSasUserRoles(String appCode, Long ausId) {
        Object _ret =
            this.riInvokeExportedMethod(this, "prepareToShowSasUserRoles",
                                        new String[] { "java.lang.String",
                                                       "java.lang.Long" },
                                        new Object[] { appCode, ausId });
        return;
    }

    public void prepareToShowAdv02OrganizationUnitsP01(Number ounId) {
        Object _ret =
            this.riInvokeExportedMethod(this, "prepareToShowAdv02OrganizationUnitsP01",
                                        new String[] { "oracle.jbo.domain.Number" },
                                        new Object[] { ounId });
        return;
    }

    public void createAppLogin(String userName, String envId, String browser,
                               Date loginAt, String ipAddress,
                               String country) {
        Object _ret =
            this.riInvokeExportedMethod(this, "createAppLogin", new String[] { "java.lang.String",
                                                                               "java.lang.String",
                                                                               "java.lang.String",
                                                                               "oracle.jbo.domain.Date",
                                                                               "java.lang.String",
                                                                               "java.lang.String" },
                                        new Object[] { userName, envId,
                                                       browser, loginAt,
                                                       ipAddress, country });
        return;
    }

    public void prepareToShowAppLogins() {
        Object _ret =
            this.riInvokeExportedMethod(this, "prepareToShowAppLogins", null,
                                        null);
        return;
    }

    public void prepareToShowDiagramProcesses(String appCode) {
        Object _ret =
            this.riInvokeExportedMethod(this, "prepareToShowDiagramProcesses",
                                        new String[] { "java.lang.String" },
                                        new Object[] { appCode });
        return;
    }

    public boolean doChangePassword(Long ausId, String newPassword) {
        Object _ret =
            this.riInvokeExportedMethod(this, "doChangePassword", new String[] { "java.lang.Long",
                                                                                 "java.lang.String" },
                                        new Object[] { ausId, newPassword });
        return ((Boolean)_ret).booleanValue();
    }
}
