package com.perp.sasregistmodel.views;

import com.perp.sasregistmodel.entities.LoginHistoriesImpl;

import com.perp.sasregistmodel.views.common.LoginHistoriesViewRow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 14 11:47:03 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoginHistoriesViewRowImpl extends ViewRowImpl implements LoginHistoriesViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LhiId {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getLhiId();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setLhiId((Number)value);
            }
        }
        ,
        EnvId {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getEnvId();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setEnvId((String)value);
            }
        }
        ,
        LoginAt {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getLoginAt();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setLoginAt((Date)value);
            }
        }
        ,
        UserName {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getUserName();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setUserName((String)value);
            }
        }
        ,
        IpAddress {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getIpAddress();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setIpAddress((String)value);
            }
        }
        ,
        Module {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getModule();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setModule((String)value);
            }
        }
        ,
        Platform {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getPlatform();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setPlatform((String)value);
            }
        }
        ,
        UserAgent {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getUserAgent();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setUserAgent((String)value);
            }
        }
        ,
        Country {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getCountry();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        LogoutAt {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getLogoutAt();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setLogoutAt((Date)value);
            }
        }
        ,
        Status {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        AccId {
            public Object get(LoginHistoriesViewRowImpl obj) {
                return obj.getAccId();
            }

            public void put(LoginHistoriesViewRowImpl obj, Object value) {
                obj.setAccId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LoginHistoriesViewRowImpl object);

        public abstract void put(LoginHistoriesViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LHIID = AttributesEnum.LhiId.index();
    public static final int ENVID = AttributesEnum.EnvId.index();
    public static final int LOGINAT = AttributesEnum.LoginAt.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int IPADDRESS = AttributesEnum.IpAddress.index();
    public static final int MODULE = AttributesEnum.Module.index();
    public static final int PLATFORM = AttributesEnum.Platform.index();
    public static final int USERAGENT = AttributesEnum.UserAgent.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int LOGOUTAT = AttributesEnum.LogoutAt.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ACCID = AttributesEnum.AccId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoginHistoriesViewRowImpl() {
    }

    /**
     * Gets LoginHistories entity object.
     * @return the LoginHistories
     */
    public LoginHistoriesImpl getLoginHistories() {
        return (LoginHistoriesImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LHI_ID using the alias name LhiId.
     * @return the LHI_ID
     */
    public Number getLhiId() {
        return (Number) getAttributeInternal(LHIID);
    }

    /**
     * Sets <code>value</code> as attribute value for LHI_ID using the alias name LhiId.
     * @param value value to set the LHI_ID
     */
    public void setLhiId(Number value) {
        setAttributeInternal(LHIID, value);
    }

    /**
     * Gets the attribute value for ENV_ID using the alias name EnvId.
     * @return the ENV_ID
     */
    public String getEnvId() {
        return (String) getAttributeInternal(ENVID);
    }

    /**
     * Sets <code>value</code> as attribute value for ENV_ID using the alias name EnvId.
     * @param value value to set the ENV_ID
     */
    public void setEnvId(String value) {
        setAttributeInternal(ENVID, value);
    }

    /**
     * Gets the attribute value for LOGIN_AT using the alias name LoginAt.
     * @return the LOGIN_AT
     */
    public Date getLoginAt() {
        return (Date) getAttributeInternal(LOGINAT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOGIN_AT using the alias name LoginAt.
     * @param value value to set the LOGIN_AT
     */
    public void setLoginAt(Date value) {
        setAttributeInternal(LOGINAT, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for IP_ADDRESS using the alias name IpAddress.
     * @return the IP_ADDRESS
     */
    public String getIpAddress() {
        return (String) getAttributeInternal(IPADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for IP_ADDRESS using the alias name IpAddress.
     * @param value value to set the IP_ADDRESS
     */
    public void setIpAddress(String value) {
        setAttributeInternal(IPADDRESS, value);
    }

    /**
     * Gets the attribute value for MODULE using the alias name Module.
     * @return the MODULE
     */
    public String getModule() {
        return (String) getAttributeInternal(MODULE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE using the alias name Module.
     * @param value value to set the MODULE
     */
    public void setModule(String value) {
        setAttributeInternal(MODULE, value);
    }

    /**
     * Gets the attribute value for PLATFORM using the alias name Platform.
     * @return the PLATFORM
     */
    public String getPlatform() {
        return (String) getAttributeInternal(PLATFORM);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATFORM using the alias name Platform.
     * @param value value to set the PLATFORM
     */
    public void setPlatform(String value) {
        setAttributeInternal(PLATFORM, value);
    }

    /**
     * Gets the attribute value for USER_AGENT using the alias name UserAgent.
     * @return the USER_AGENT
     */
    public String getUserAgent() {
        return (String) getAttributeInternal(USERAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_AGENT using the alias name UserAgent.
     * @param value value to set the USER_AGENT
     */
    public void setUserAgent(String value) {
        setAttributeInternal(USERAGENT, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for LOGOUT_AT using the alias name LogoutAt.
     * @return the LOGOUT_AT
     */
    public Date getLogoutAt() {
        return (Date) getAttributeInternal(LOGOUTAT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOGOUT_AT using the alias name LogoutAt.
     * @param value value to set the LOGOUT_AT
     */
    public void setLogoutAt(Date value) {
        setAttributeInternal(LOGOUTAT, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ACC_ID using the alias name AccId.
     * @return the ACC_ID
     */
    public Number getAccId() {
        return (Number) getAttributeInternal(ACCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_ID using the alias name AccId.
     * @param value value to set the ACC_ID
     */
    public void setAccId(Number value) {
        setAttributeInternal(ACCID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
