package com.vc.sasnmodel.views.sasn.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 07 11:49:04 ICT 2014
// ---------------------------------------------------------------------
public interface ContactInfosViewRow extends Row {
    String getAddress();

    void setAddress(String value);

    String getAttribute1();

    void setAttribute1(String value);

    String getAttribute2();

    void setAttribute2(String value);

    String getAttribute3();

    void setAttribute3(String value);

    String getAttribute4();

    void setAttribute4(String value);

    String getAttribute5();

    void setAttribute5(String value);

    Number getCinId();

    void setCinId(Number value);

    String getCompanyName();

    void setCompanyName(String value);

    String getConfirmCode();

    void setConfirmCode(String value);

    String getContactName();

    void setContactName(String value);

    String getContent();

    void setContent(String value);

    String getCountry();

    void setCountry(String value);

    String getCreatedBy();

    void setCreatedBy(String value);

    Date getCreateDate();

    void setCreateDate(Date value);

    String getEmailAddress();

    void setEmailAddress(String value);

    String getModifiedBy();

    void setModifiedBy(String value);

    Date getModifyDate();

    void setModifyDate(Date value);

    String getPhoneNumber();

    void setPhoneNumber(String value);
}
