package com.vc.sasnmodel.views.sasn.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 14 10:24:49 ICT 2010
// ---------------------------------------------------------------------
public interface GuestQuestionsRow extends Row {
    Number getGquId();

    void setGquId(Number value);

    String getTitle();

    void setTitle(String value);

    String getContent();

    void setContent(String value);

    Date getQuestionDate();

    void setQuestionDate(Date value);

    String getGuestEmail();

    void setGuestEmail(String value);

    String getGuestTelephone();

    void setGuestTelephone(String value);

    Number getAgrId();

    void setAgrId(Number value);

    String getAnswerMail();

    void setAnswerMail(String value);

    String getAnswerFlag();

    void setAnswerFlag(String value);
}
