package com.vc.sasnmodel.views.sasn.common;

import oracle.jbo.Row;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 22 00:44:36 ICT 2010
// ---------------------------------------------------------------------
public interface NewsRow extends Row {
    Number getNewsId();

    void setNewsId(Number value);

    Number getNcaId();

    void setNcaId(Number value);

    String getTitle();

    void setTitle(String value);

    ClobDomain getContent();

    void setContent(ClobDomain value);

    Number getPriorityLevel();

    void setPriorityLevel(Number value);

    Date getCreateDate();

    void setCreateDate(Date value);

    String getCreatedBy();

    void setCreatedBy(String value);

    Date getModifyDate();

    void setModifyDate(Date value);

    String getModifiedBy();

    void setModifiedBy(String value);

    String getShortContent();

    void setShortContent(String value);

    String getBookmarkCode();

    void setBookmarkCode(String value);

    Number getIreIdSmall();

    void setIreIdSmall(Number value);

    Number getIreIdMedium();

    void setIreIdMedium(Number value);

    Date getNewsDate();

    void setNewsDate(Date value);
}
