package com.perp.sasregistmodel.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 14 11:45:51 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoginHistoriesImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LhiId {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getLhiId();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setLhiId((Number)value);
            }
        }
        ,
        EnvId {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getEnvId();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setEnvId((String)value);
            }
        }
        ,
        LoginAt {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getLoginAt();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setLoginAt((Date)value);
            }
        }
        ,
        UserName {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getUserName();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setUserName((String)value);
            }
        }
        ,
        IpAddress {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getIpAddress();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setIpAddress((String)value);
            }
        }
        ,
        Module {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getModule();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setModule((String)value);
            }
        }
        ,
        Platform {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getPlatform();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setPlatform((String)value);
            }
        }
        ,
        UserAgent {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getUserAgent();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setUserAgent((String)value);
            }
        }
        ,
        Country {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getCountry();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        LogoutAt {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getLogoutAt();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setLogoutAt((Date)value);
            }
        }
        ,
        Status {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getStatus();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAttribute1();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAttribute2();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAttribute3();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAttribute4();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAttribute5();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        AccId {
            public Object get(LoginHistoriesImpl obj) {
                return obj.getAccId();
            }

            public void put(LoginHistoriesImpl obj, Object value) {
                obj.setAccId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LoginHistoriesImpl object);

        public abstract void put(LoginHistoriesImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LHIID = AttributesEnum.LhiId.index();
    public static final int ENVID = AttributesEnum.EnvId.index();
    public static final int LOGINAT = AttributesEnum.LoginAt.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int IPADDRESS = AttributesEnum.IpAddress.index();
    public static final int MODULE = AttributesEnum.Module.index();
    public static final int PLATFORM = AttributesEnum.Platform.index();
    public static final int USERAGENT = AttributesEnum.UserAgent.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int LOGOUTAT = AttributesEnum.LogoutAt.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ACCID = AttributesEnum.AccId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoginHistoriesImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.perp.sasregistmodel.entities.LoginHistories");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LhiId, using the alias name LhiId.
     * @return the LhiId
     */
    public Number getLhiId() {
        return (Number)getAttributeInternal(LHIID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LhiId.
     * @param value value to set the LhiId
     */
    public void setLhiId(Number value) {
        setAttributeInternal(LHIID, value);
    }

    /**
     * Gets the attribute value for EnvId, using the alias name EnvId.
     * @return the EnvId
     */
    public String getEnvId() {
        return (String)getAttributeInternal(ENVID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnvId.
     * @param value value to set the EnvId
     */
    public void setEnvId(String value) {
        setAttributeInternal(ENVID, value);
    }

    /**
     * Gets the attribute value for LoginAt, using the alias name LoginAt.
     * @return the LoginAt
     */
    public Date getLoginAt() {
        return (Date)getAttributeInternal(LOGINAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoginAt.
     * @param value value to set the LoginAt
     */
    public void setLoginAt(Date value) {
        setAttributeInternal(LOGINAT, value);
    }

    /**
     * Gets the attribute value for UserName, using the alias name UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String)getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserName.
     * @param value value to set the UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for IpAddress, using the alias name IpAddress.
     * @return the IpAddress
     */
    public String getIpAddress() {
        return (String)getAttributeInternal(IPADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IpAddress.
     * @param value value to set the IpAddress
     */
    public void setIpAddress(String value) {
        setAttributeInternal(IPADDRESS, value);
    }

    /**
     * Gets the attribute value for Module, using the alias name Module.
     * @return the Module
     */
    public String getModule() {
        return (String)getAttributeInternal(MODULE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Module.
     * @param value value to set the Module
     */
    public void setModule(String value) {
        setAttributeInternal(MODULE, value);
    }

    /**
     * Gets the attribute value for Platform, using the alias name Platform.
     * @return the Platform
     */
    public String getPlatform() {
        return (String)getAttributeInternal(PLATFORM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Platform.
     * @param value value to set the Platform
     */
    public void setPlatform(String value) {
        setAttributeInternal(PLATFORM, value);
    }

    /**
     * Gets the attribute value for UserAgent, using the alias name UserAgent.
     * @return the UserAgent
     */
    public String getUserAgent() {
        return (String)getAttributeInternal(USERAGENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserAgent.
     * @param value value to set the UserAgent
     */
    public void setUserAgent(String value) {
        setAttributeInternal(USERAGENT, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for LogoutAt, using the alias name LogoutAt.
     * @return the LogoutAt
     */
    public Date getLogoutAt() {
        return (Date)getAttributeInternal(LOGOUTAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LogoutAt.
     * @param value value to set the LogoutAt
     */
    public void setLogoutAt(Date value) {
        setAttributeInternal(LOGOUTAT, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for AccId, using the alias name AccId.
     * @return the AccId
     */
    public Number getAccId() {
        return (Number)getAttributeInternal(ACCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccId.
     * @param value value to set the AccId
     */
    public void setAccId(Number value) {
        setAttributeInternal(ACCID, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param lhiId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lhiId) {
        return new Key(new Object[]{lhiId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}
