package com.perp.sasregistmodel.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 08 14:05:51 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccountsRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AccountsRowClient() {
    }


    public Number getAccId() {
        return (Number)getAttribute("AccId");
    }

    public void setAccId(Number value) {
        setAttribute("AccId", value);
    }

    public String getFullName() {
        return (String)getAttribute("FullName");
    }

    public void setFullName(String value) {
        setAttribute("FullName", value);
    }

    public String getContactTelephone() {
        return (String)getAttribute("ContactTelephone");
    }

    public void setContactTelephone(String value) {
        setAttribute("ContactTelephone", value);
    }

    public String getEmail() {
        return (String)getAttribute("Email");
    }

    public void setEmail(String value) {
        setAttribute("Email", value);
    }

    public String getOrganizationName() {
        return (String)getAttribute("OrganizationName");
    }

    public void setOrganizationName(String value) {
        setAttribute("OrganizationName", value);
    }

    public Number getProId() {
        return (Number)getAttribute("ProId");
    }

    public void setProId(Number value) {
        setAttribute("ProId", value);
    }

    public String getAddress() {
        return (String)getAttribute("Address");
    }

    public void setAddress(String value) {
        setAttribute("Address", value);
    }

    public String getTaxCode() {
        return (String)getAttribute("TaxCode");
    }

    public void setTaxCode(String value) {
        setAttribute("TaxCode", value);
    }

    public Number getRolId() {
        return (Number)getAttribute("RolId");
    }

    public void setRolId(Number value) {
        setAttribute("RolId", value);
    }

    public Number getNumberOfEmployee() {
        return (Number)getAttribute("NumberOfEmployee");
    }

    public void setNumberOfEmployee(Number value) {
        setAttribute("NumberOfEmployee", value);
    }

    public String getCustomerApproach() {
        return (String)getAttribute("CustomerApproach");
    }

    public void setCustomerApproach(String value) {
        setAttribute("CustomerApproach", value);
    }

    public String getUserName() {
        return (String)getAttribute("UserName");
    }

    public void setUserName(String value) {
        setAttribute("UserName", value);
    }

    public String getPassword() {
        return (String)getAttribute("Password");
    }

    public void setPassword(String value) {
        setAttribute("Password", value);
    }

    public String getActivedCode() {
        return (String)getAttribute("ActivedCode");
    }

    public void setActivedCode(String value) {
        setAttribute("ActivedCode", value);
    }

    public Number getCouId() {
        return (Number)getAttribute("CouId");
    }

    public void setCouId(Number value) {
        setAttribute("CouId", value);
    }

    public Number getIndId() {
        return (Number)getAttribute("IndId");
    }

    public void setIndId(Number value) {
        setAttribute("IndId", value);
    }

    public String getStatus() {
        return (String)getAttribute("Status");
    }

    public void setStatus(String value) {
        setAttribute("Status", value);
    }

    public Number getSquId() {
        return (Number)getAttribute("SquId");
    }

    public void setSquId(Number value) {
        setAttribute("SquId", value);
    }

    public String getSecurityAnswer() {
        return (String)getAttribute("SecurityAnswer");
    }

    public void setSecurityAnswer(String value) {
        setAttribute("SecurityAnswer", value);
    }

    public Number getMmeId() {
        return (Number)getAttribute("MmeId");
    }

    public void setMmeId(Number value) {
        setAttribute("MmeId", value);
    }

    public Number getLabId() {
        return (Number)getAttribute("LabId");
    }

    public void setLabId(Number value) {
        setAttribute("LabId", value);
    }

    public String getActivatedFlag() {
        return (String)getAttribute("ActivatedFlag");
    }

    public void setActivatedFlag(String value) {
        setAttribute("ActivatedFlag", value);
    }

    public void setIsAdmin(String value) {
        setAttribute("IsAdmin", value);
    }

    public String getIsAdmin() {
        return (String)getAttribute("IsAdmin");
    }
}
