package com.perp.sasregistmodel.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 14 11:48:11 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoginHistoriesViewRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoginHistoriesViewRowClient() {
    }


    public void setUserName(String value) {
        setAttribute("UserName", value);
    }

    public void setUserAgent(String value) {
        setAttribute("UserAgent", value);
    }

    public void setPlatform(String value) {
        setAttribute("Platform", value);
    }

    public void setModule(String value) {
        setAttribute("Module", value);
    }

    public void setLogoutAt(Date value) {
        setAttribute("LogoutAt", value);
    }

    public void setLoginAt(Date value) {
        setAttribute("LoginAt", value);
    }

    public void setLhiId(Number value) {
        setAttribute("LhiId", value);
    }

    public void setIpAddress(String value) {
        setAttribute("IpAddress", value);
    }

    public void setEnvId(String value) {
        setAttribute("EnvId", value);
    }

    public void setCountry(String value) {
        setAttribute("Country", value);
    }

    public void setAttribute5(String value) {
        setAttribute("Attribute5", value);
    }

    public void setAttribute4(String value) {
        setAttribute("Attribute4", value);
    }

    public void setAttribute3(String value) {
        setAttribute("Attribute3", value);
    }

    public void setAttribute2(String value) {
        setAttribute("Attribute2", value);
    }

    public void setAttribute1(String value) {
        setAttribute("Attribute1", value);
    }

    public String getUserName() {
        return (String)getAttribute("UserName");
    }

    public String getUserAgent() {
        return (String)getAttribute("UserAgent");
    }

    public String getPlatform() {
        return (String)getAttribute("Platform");
    }

    public String getModule() {
        return (String)getAttribute("Module");
    }

    public Date getLogoutAt() {
        return (Date)getAttribute("LogoutAt");
    }

    public Date getLoginAt() {
        return (Date)getAttribute("LoginAt");
    }

    public Number getLhiId() {
        return (Number)getAttribute("LhiId");
    }

    public String getIpAddress() {
        return (String)getAttribute("IpAddress");
    }

    public String getEnvId() {
        return (String)getAttribute("EnvId");
    }

    public String getCountry() {
        return (String)getAttribute("Country");
    }

    public String getAttribute5() {
        return (String)getAttribute("Attribute5");
    }

    public String getAttribute4() {
        return (String)getAttribute("Attribute4");
    }

    public String getAttribute3() {
        return (String)getAttribute("Attribute3");
    }

    public String getAttribute2() {
        return (String)getAttribute("Attribute2");
    }

    public String getAttribute1() {
        return (String)getAttribute("Attribute1");
    }

    public void setStatus(String value) {
        setAttribute("Status", value);
    }

    public String getStatus() {
        return (String)getAttribute("Status");
    }

    public void setAccId(Number value) {
        setAttribute("AccId", value);
    }

    public Number getAccId() {
        return (Number)getAttribute("AccId");
    }
}
