package com.vc.sasnmodel.views.sasn;

import com.vc.sasnmodel.views.sasn.common.DocumentDownloadsRow;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 15 09:27:36 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentDownloadsRowImpl extends ViewRowImpl implements DocumentDownloadsRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DdoId {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDdoId();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDdoId((Number)value);
            }
        }
        ,
        DcaId {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDcaId();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDcaId((Number)value);
            }
        }
        ,
        Title {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getTitle();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setTitle((String)value);
            }
        }
        ,
        ShortContent {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getShortContent();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setShortContent((String)value);
            }
        }
        ,
        PublicDate {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getPublicDate();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setPublicDate((Date)value);
            }
        }
        ,
        DownloadLink {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDownloadLink();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDownloadLink((String)value);
            }
        }
        ,
        DownloadData {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDownloadData();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDownloadData((BlobDomain)value);
            }
        }
        ,
        DataSize {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDataSize();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDataSize((Number)value);
            }
        }
        ,
        DownloadCount {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDownloadCount();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setDownloadCount((Number)value);
            }
        }
        ,
        PriorityOrder {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getPriorityOrder();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setPriorityOrder((Number)value);
            }
        }
        ,
        FileName {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getFileName();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        FileType {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getFileType();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setFileType((String)value);
            }
        }
        ,
        DocumentCategories {
            public Object get(DocumentDownloadsRowImpl obj) {
                return obj.getDocumentCategories();
            }

            public void put(DocumentDownloadsRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DocumentDownloadsRowImpl object);

        public abstract void put(DocumentDownloadsRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int DDOID = AttributesEnum.DdoId.index();
    public static final int DCAID = AttributesEnum.DcaId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int SHORTCONTENT = AttributesEnum.ShortContent.index();
    public static final int PUBLICDATE = AttributesEnum.PublicDate.index();
    public static final int DOWNLOADLINK = AttributesEnum.DownloadLink.index();
    public static final int DOWNLOADDATA = AttributesEnum.DownloadData.index();
    public static final int DATASIZE = AttributesEnum.DataSize.index();
    public static final int DOWNLOADCOUNT = AttributesEnum.DownloadCount.index();
    public static final int PRIORITYORDER = AttributesEnum.PriorityOrder.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int FILETYPE = AttributesEnum.FileType.index();
    public static final int DOCUMENTCATEGORIES = AttributesEnum.DocumentCategories.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DocumentDownloadsRowImpl() {
    }

    /**
     * Gets DocumentDownloads entity object.
     * @return the DocumentDownloads
     */
    public EntityImpl getDocumentDownloads() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DDO_ID using the alias name DdoId.
     * @return the DDO_ID
     */
    public Number getDdoId() {
        return (Number) getAttributeInternal(DDOID);
    }

    /**
     * Sets <code>value</code> as attribute value for DDO_ID using the alias name DdoId.
     * @param value value to set the DDO_ID
     */
    public void setDdoId(Number value) {
        setAttributeInternal(DDOID, value);
    }

    /**
     * Gets the attribute value for DCA_ID using the alias name DcaId.
     * @return the DCA_ID
     */
    public Number getDcaId() {
        return (Number) getAttributeInternal(DCAID);
    }

    /**
     * Sets <code>value</code> as attribute value for DCA_ID using the alias name DcaId.
     * @param value value to set the DCA_ID
     */
    public void setDcaId(Number value) {
        setAttributeInternal(DCAID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for SHORT_CONTENT using the alias name ShortContent.
     * @return the SHORT_CONTENT
     */
    public String getShortContent() {
        return (String) getAttributeInternal(SHORTCONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHORT_CONTENT using the alias name ShortContent.
     * @param value value to set the SHORT_CONTENT
     */
    public void setShortContent(String value) {
        setAttributeInternal(SHORTCONTENT, value);
    }

    /**
     * Gets the attribute value for PUBLIC_DATE using the alias name PublicDate.
     * @return the PUBLIC_DATE
     */
    public Date getPublicDate() {
        return (Date) getAttributeInternal(PUBLICDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PUBLIC_DATE using the alias name PublicDate.
     * @param value value to set the PUBLIC_DATE
     */
    public void setPublicDate(Date value) {
        setAttributeInternal(PUBLICDATE, value);
    }

    /**
     * Gets the attribute value for DOWNLOAD_LINK using the alias name DownloadLink.
     * @return the DOWNLOAD_LINK
     */
    public String getDownloadLink() {
        return (String) getAttributeInternal(DOWNLOADLINK);
    }

    /**
     * Sets <code>value</code> as attribute value for DOWNLOAD_LINK using the alias name DownloadLink.
     * @param value value to set the DOWNLOAD_LINK
     */
    public void setDownloadLink(String value) {
        setAttributeInternal(DOWNLOADLINK, value);
    }

    /**
     * Gets the attribute value for DOWNLOAD_DATA using the alias name DownloadData.
     * @return the DOWNLOAD_DATA
     */
    public BlobDomain getDownloadData() {
        return (BlobDomain) getAttributeInternal(DOWNLOADDATA);
    }

    /**
     * Sets <code>value</code> as attribute value for DOWNLOAD_DATA using the alias name DownloadData.
     * @param value value to set the DOWNLOAD_DATA
     */
    public void setDownloadData(BlobDomain value) {
        setAttributeInternal(DOWNLOADDATA, value);
    }

    /**
     * Gets the attribute value for DATA_SIZE using the alias name DataSize.
     * @return the DATA_SIZE
     */
    public Number getDataSize() {
        return (Number) getAttributeInternal(DATASIZE);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SIZE using the alias name DataSize.
     * @param value value to set the DATA_SIZE
     */
    public void setDataSize(Number value) {
        setAttributeInternal(DATASIZE, value);
    }

    /**
     * Gets the attribute value for DOWNLOAD_COUNT using the alias name DownloadCount.
     * @return the DOWNLOAD_COUNT
     */
    public Number getDownloadCount() {
        return (Number) getAttributeInternal(DOWNLOADCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOWNLOAD_COUNT using the alias name DownloadCount.
     * @param value value to set the DOWNLOAD_COUNT
     */
    public void setDownloadCount(Number value) {
        setAttributeInternal(DOWNLOADCOUNT, value);
    }

    /**
     * Gets the attribute value for PRIORITY_ORDER using the alias name PriorityOrder.
     * @return the PRIORITY_ORDER
     */
    public Number getPriorityOrder() {
        return (Number) getAttributeInternal(PRIORITYORDER);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_ORDER using the alias name PriorityOrder.
     * @param value value to set the PRIORITY_ORDER
     */
    public void setPriorityOrder(Number value) {
        setAttributeInternal(PRIORITYORDER, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for FILE_TYPE using the alias name FileType.
     * @return the FILE_TYPE
     */
    public String getFileType() {
        return (String) getAttributeInternal(FILETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_TYPE using the alias name FileType.
     * @param value value to set the FILE_TYPE
     */
    public void setFileType(String value) {
        setAttributeInternal(FILETYPE, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link DocumentCategories.
     */
    public Row getDocumentCategories() {
        return (Row)getAttributeInternal(DOCUMENTCATEGORIES);
    }

    /**
     * Sets the master-detail link DocumentCategories between this object and <code>value</code>.
     */
    public void setDocumentCategories(Row value) {
        setAttributeInternal(DOCUMENTCATEGORIES, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
