package com.vc.sasnmodel.views.sasn;

import com.vc.sasnmodel.entities.NewsImpl;

import com.vc.sasnmodel.views.sasn.common.NewsRow;

import oracle.jbo.Row;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 22 00:44:36 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsRowImpl extends ViewRowImpl implements NewsRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        NewsId {
            public Object get(NewsRowImpl obj) {
                return obj.getNewsId();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setNewsId((Number)value);
            }
        }
        ,
        NcaId {
            public Object get(NewsRowImpl obj) {
                return obj.getNcaId();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setNcaId((Number)value);
            }
        }
        ,
        Title {
            public Object get(NewsRowImpl obj) {
                return obj.getTitle();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setTitle((String)value);
            }
        }
        ,
        Content {
            public Object get(NewsRowImpl obj) {
                return obj.getContent();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setContent((ClobDomain)value);
            }
        }
        ,
        PriorityLevel {
            public Object get(NewsRowImpl obj) {
                return obj.getPriorityLevel();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setPriorityLevel((Number)value);
            }
        }
        ,
        CreateDate {
            public Object get(NewsRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(NewsRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        ModifyDate {
            public Object get(NewsRowImpl obj) {
                return obj.getModifyDate();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setModifyDate((Date)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(NewsRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ShortContent {
            public Object get(NewsRowImpl obj) {
                return obj.getShortContent();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setShortContent((String)value);
            }
        }
        ,
        BookmarkCode {
            public Object get(NewsRowImpl obj) {
                return obj.getBookmarkCode();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setBookmarkCode((String)value);
            }
        }
        ,
        IreIdSmall {
            public Object get(NewsRowImpl obj) {
                return obj.getIreIdSmall();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setIreIdSmall((Number)value);
            }
        }
        ,
        IreIdMedium {
            public Object get(NewsRowImpl obj) {
                return obj.getIreIdMedium();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setIreIdMedium((Number)value);
            }
        }
        ,
        NewsDate {
            public Object get(NewsRowImpl obj) {
                return obj.getNewsDate();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setNewsDate((Date)value);
            }
        }
        ,
        NewsCategories {
            public Object get(NewsRowImpl obj) {
                return obj.getNewsCategories();
            }

            public void put(NewsRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(NewsRowImpl object);

        public abstract void put(NewsRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int NEWSID = AttributesEnum.NewsId.index();
    public static final int NCAID = AttributesEnum.NcaId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int CONTENT = AttributesEnum.Content.index();
    public static final int PRIORITYLEVEL = AttributesEnum.PriorityLevel.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int MODIFYDATE = AttributesEnum.ModifyDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int SHORTCONTENT = AttributesEnum.ShortContent.index();
    public static final int BOOKMARKCODE = AttributesEnum.BookmarkCode.index();
    public static final int IREIDSMALL = AttributesEnum.IreIdSmall.index();
    public static final int IREIDMEDIUM = AttributesEnum.IreIdMedium.index();
    public static final int NEWSDATE = AttributesEnum.NewsDate.index();
    public static final int NEWSCATEGORIES = AttributesEnum.NewsCategories.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NewsRowImpl() {
    }

    /**
     * Gets News entity object.
     * @return the News
     */
    public NewsImpl getNews() {
        return (NewsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for NEWS_ID using the alias name NewsId.
     * @return the NEWS_ID
     */
    public Number getNewsId() {
        return (Number) getAttributeInternal(NEWSID);
    }

    /**
     * Sets <code>value</code> as attribute value for NEWS_ID using the alias name NewsId.
     * @param value value to set the NEWS_ID
     */
    public void setNewsId(Number value) {
        setAttributeInternal(NEWSID, value);
    }

    /**
     * Gets the attribute value for NCA_ID using the alias name NcaId.
     * @return the NCA_ID
     */
    public Number getNcaId() {
        return (Number) getAttributeInternal(NCAID);
    }

    /**
     * Sets <code>value</code> as attribute value for NCA_ID using the alias name NcaId.
     * @param value value to set the NCA_ID
     */
    public void setNcaId(Number value) {
        setAttributeInternal(NCAID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for CONTENT using the alias name Content.
     * @return the CONTENT
     */
    public ClobDomain getContent() {
        return (ClobDomain) getAttributeInternal(CONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTENT using the alias name Content.
     * @param value value to set the CONTENT
     */
    public void setContent(ClobDomain value) {
        setAttributeInternal(CONTENT, value);
    }

    /**
     * Gets the attribute value for PRIORITY_LEVEL using the alias name PriorityLevel.
     * @return the PRIORITY_LEVEL
     */
    public Number getPriorityLevel() {
        return (Number) getAttributeInternal(PRIORITYLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_LEVEL using the alias name PriorityLevel.
     * @param value value to set the PRIORITY_LEVEL
     */
    public void setPriorityLevel(Number value) {
        setAttributeInternal(PRIORITYLEVEL, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @return the MODIFY_DATE
     */
    public Date getModifyDate() {
        return (Date) getAttributeInternal(MODIFYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @param value value to set the MODIFY_DATE
     */
    public void setModifyDate(Date value) {
        setAttributeInternal(MODIFYDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for SHORT_CONTENT using the alias name ShortContent.
     * @return the SHORT_CONTENT
     */
    public String getShortContent() {
        return (String) getAttributeInternal(SHORTCONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHORT_CONTENT using the alias name ShortContent.
     * @param value value to set the SHORT_CONTENT
     */
    public void setShortContent(String value) {
        setAttributeInternal(SHORTCONTENT, value);
    }

    /**
     * Gets the attribute value for BOOKMARK_CODE using the alias name BookmarkCode.
     * @return the BOOKMARK_CODE
     */
    public String getBookmarkCode() {
        return (String) getAttributeInternal(BOOKMARKCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKMARK_CODE using the alias name BookmarkCode.
     * @param value value to set the BOOKMARK_CODE
     */
    public void setBookmarkCode(String value) {
        setAttributeInternal(BOOKMARKCODE, value);
    }

    /**
     * Gets the attribute value for IRE_ID_SMALL using the alias name IreIdSmall.
     * @return the IRE_ID_SMALL
     */
    public Number getIreIdSmall() {
        return (Number) getAttributeInternal(IREIDSMALL);
    }

    /**
     * Sets <code>value</code> as attribute value for IRE_ID_SMALL using the alias name IreIdSmall.
     * @param value value to set the IRE_ID_SMALL
     */
    public void setIreIdSmall(Number value) {
        setAttributeInternal(IREIDSMALL, value);
    }

    /**
     * Gets the attribute value for IRE_ID_MEDIUM using the alias name IreIdMedium.
     * @return the IRE_ID_MEDIUM
     */
    public Number getIreIdMedium() {
        return (Number) getAttributeInternal(IREIDMEDIUM);
    }

    /**
     * Sets <code>value</code> as attribute value for IRE_ID_MEDIUM using the alias name IreIdMedium.
     * @param value value to set the IRE_ID_MEDIUM
     */
    public void setIreIdMedium(Number value) {
        setAttributeInternal(IREIDMEDIUM, value);
    }

    /**
     * Gets the attribute value for NEWS_DATE using the alias name NewsDate.
     * @return the NEWS_DATE
     */
    public Date getNewsDate() {
        return (Date) getAttributeInternal(NEWSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEWS_DATE using the alias name NewsDate.
     * @param value value to set the NEWS_DATE
     */
    public void setNewsDate(Date value) {
        setAttributeInternal(NEWSDATE, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link NewsCategories.
     */
    public Row getNewsCategories() {
        return (Row)getAttributeInternal(NEWSCATEGORIES);
    }

    /**
     * Sets the master-detail link NewsCategories between this object and <code>value</code>.
     */
    public void setNewsCategories(Row value) {
        setAttributeInternal(NEWSCATEGORIES, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
