package com.vc.sasnmodel.views.sasn;

import com.vc.sasnmodel.entities.PartnersImpl;

import com.vc.sasnmodel.views.sasn.common.PartnersRow;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 22 10:48:20 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartnersRowImpl extends ViewRowImpl implements PartnersRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ParId {
            public Object get(PartnersRowImpl obj) {
                return obj.getParId();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setParId((Number)value);
            }
        }
        ,
        PgrId {
            public Object get(PartnersRowImpl obj) {
                return obj.getPgrId();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setPgrId((Number)value);
            }
        }
        ,
        CompanyName {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyName();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyName((String)value);
            }
        }
        ,
        CompanyAddress {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyAddress();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyAddress((String)value);
            }
        }
        ,
        CompanyTelephone {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyTelephone();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyTelephone((String)value);
            }
        }
        ,
        CompanyFax {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyFax();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyFax((String)value);
            }
        }
        ,
        CompanyEmail {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyEmail();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyEmail((String)value);
            }
        }
        ,
        CompanyWebsite {
            public Object get(PartnersRowImpl obj) {
                return obj.getCompanyWebsite();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCompanyWebsite((String)value);
            }
        }
        ,
        ContactPersonName {
            public Object get(PartnersRowImpl obj) {
                return obj.getContactPersonName();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setContactPersonName((String)value);
            }
        }
        ,
        ContactPersonPosition {
            public Object get(PartnersRowImpl obj) {
                return obj.getContactPersonPosition();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setContactPersonPosition((String)value);
            }
        }
        ,
        ContactPersonTelephone {
            public Object get(PartnersRowImpl obj) {
                return obj.getContactPersonTelephone();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setContactPersonTelephone((String)value);
            }
        }
        ,
        ContactPersonEmail {
            public Object get(PartnersRowImpl obj) {
                return obj.getContactPersonEmail();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setContactPersonEmail((String)value);
            }
        }
        ,
        CreateDate {
            public Object get(PartnersRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PartnersRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        ModifyDate {
            public Object get(PartnersRowImpl obj) {
                return obj.getModifyDate();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setModifyDate((Date)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(PartnersRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        Description {
            public Object get(PartnersRowImpl obj) {
                return obj.getDescription();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Image {
            public Object get(PartnersRowImpl obj) {
                return obj.getImage();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setImage((BlobDomain)value);
            }
        }
        ,
        PartnerGroups {
            public Object get(PartnersRowImpl obj) {
                return obj.getPartnerGroups();
            }

            public void put(PartnersRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PartnersRowImpl object);

        public abstract void put(PartnersRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PARID = AttributesEnum.ParId.index();
    public static final int PGRID = AttributesEnum.PgrId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int COMPANYADDRESS = AttributesEnum.CompanyAddress.index();
    public static final int COMPANYTELEPHONE = AttributesEnum.CompanyTelephone.index();
    public static final int COMPANYFAX = AttributesEnum.CompanyFax.index();
    public static final int COMPANYEMAIL = AttributesEnum.CompanyEmail.index();
    public static final int COMPANYWEBSITE = AttributesEnum.CompanyWebsite.index();
    public static final int CONTACTPERSONNAME = AttributesEnum.ContactPersonName.index();
    public static final int CONTACTPERSONPOSITION = AttributesEnum.ContactPersonPosition.index();
    public static final int CONTACTPERSONTELEPHONE = AttributesEnum.ContactPersonTelephone.index();
    public static final int CONTACTPERSONEMAIL = AttributesEnum.ContactPersonEmail.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int MODIFYDATE = AttributesEnum.ModifyDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int IMAGE = AttributesEnum.Image.index();
    public static final int PARTNERGROUPS = AttributesEnum.PartnerGroups.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PartnersRowImpl() {
    }

    /**
     * Gets Partners entity object.
     * @return the Partners
     */
    public PartnersImpl getPartners() {
        return (PartnersImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PAR_ID using the alias name ParId.
     * @return the PAR_ID
     */
    public Number getParId() {
        return (Number) getAttributeInternal(PARID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAR_ID using the alias name ParId.
     * @param value value to set the PAR_ID
     */
    public void setParId(Number value) {
        setAttributeInternal(PARID, value);
    }

    /**
     * Gets the attribute value for PGR_ID using the alias name PgrId.
     * @return the PGR_ID
     */
    public Number getPgrId() {
        return (Number) getAttributeInternal(PGRID);
    }

    /**
     * Sets <code>value</code> as attribute value for PGR_ID using the alias name PgrId.
     * @param value value to set the PGR_ID
     */
    public void setPgrId(Number value) {
        setAttributeInternal(PGRID, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for COMPANY_ADDRESS using the alias name CompanyAddress.
     * @return the COMPANY_ADDRESS
     */
    public String getCompanyAddress() {
        return (String) getAttributeInternal(COMPANYADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ADDRESS using the alias name CompanyAddress.
     * @param value value to set the COMPANY_ADDRESS
     */
    public void setCompanyAddress(String value) {
        setAttributeInternal(COMPANYADDRESS, value);
    }

    /**
     * Gets the attribute value for COMPANY_TELEPHONE using the alias name CompanyTelephone.
     * @return the COMPANY_TELEPHONE
     */
    public String getCompanyTelephone() {
        return (String) getAttributeInternal(COMPANYTELEPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_TELEPHONE using the alias name CompanyTelephone.
     * @param value value to set the COMPANY_TELEPHONE
     */
    public void setCompanyTelephone(String value) {
        setAttributeInternal(COMPANYTELEPHONE, value);
    }

    /**
     * Gets the attribute value for COMPANY_FAX using the alias name CompanyFax.
     * @return the COMPANY_FAX
     */
    public String getCompanyFax() {
        return (String) getAttributeInternal(COMPANYFAX);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_FAX using the alias name CompanyFax.
     * @param value value to set the COMPANY_FAX
     */
    public void setCompanyFax(String value) {
        setAttributeInternal(COMPANYFAX, value);
    }

    /**
     * Gets the attribute value for COMPANY_EMAIL using the alias name CompanyEmail.
     * @return the COMPANY_EMAIL
     */
    public String getCompanyEmail() {
        return (String) getAttributeInternal(COMPANYEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_EMAIL using the alias name CompanyEmail.
     * @param value value to set the COMPANY_EMAIL
     */
    public void setCompanyEmail(String value) {
        setAttributeInternal(COMPANYEMAIL, value);
    }

    /**
     * Gets the attribute value for COMPANY_WEBSITE using the alias name CompanyWebsite.
     * @return the COMPANY_WEBSITE
     */
    public String getCompanyWebsite() {
        return (String) getAttributeInternal(COMPANYWEBSITE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_WEBSITE using the alias name CompanyWebsite.
     * @param value value to set the COMPANY_WEBSITE
     */
    public void setCompanyWebsite(String value) {
        setAttributeInternal(COMPANYWEBSITE, value);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON_NAME using the alias name ContactPersonName.
     * @return the CONTACT_PERSON_NAME
     */
    public String getContactPersonName() {
        return (String) getAttributeInternal(CONTACTPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON_NAME using the alias name ContactPersonName.
     * @param value value to set the CONTACT_PERSON_NAME
     */
    public void setContactPersonName(String value) {
        setAttributeInternal(CONTACTPERSONNAME, value);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON_POSITION using the alias name ContactPersonPosition.
     * @return the CONTACT_PERSON_POSITION
     */
    public String getContactPersonPosition() {
        return (String) getAttributeInternal(CONTACTPERSONPOSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON_POSITION using the alias name ContactPersonPosition.
     * @param value value to set the CONTACT_PERSON_POSITION
     */
    public void setContactPersonPosition(String value) {
        setAttributeInternal(CONTACTPERSONPOSITION, value);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON_TELEPHONE using the alias name ContactPersonTelephone.
     * @return the CONTACT_PERSON_TELEPHONE
     */
    public String getContactPersonTelephone() {
        return (String) getAttributeInternal(CONTACTPERSONTELEPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON_TELEPHONE using the alias name ContactPersonTelephone.
     * @param value value to set the CONTACT_PERSON_TELEPHONE
     */
    public void setContactPersonTelephone(String value) {
        setAttributeInternal(CONTACTPERSONTELEPHONE, value);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON_EMAIL using the alias name ContactPersonEmail.
     * @return the CONTACT_PERSON_EMAIL
     */
    public String getContactPersonEmail() {
        return (String) getAttributeInternal(CONTACTPERSONEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON_EMAIL using the alias name ContactPersonEmail.
     * @param value value to set the CONTACT_PERSON_EMAIL
     */
    public void setContactPersonEmail(String value) {
        setAttributeInternal(CONTACTPERSONEMAIL, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @return the MODIFY_DATE
     */
    public Date getModifyDate() {
        return (Date) getAttributeInternal(MODIFYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @param value value to set the MODIFY_DATE
     */
    public void setModifyDate(Date value) {
        setAttributeInternal(MODIFYDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for IMAGE using the alias name Image.
     * @return the IMAGE
     */
    public BlobDomain getImage() {
        return (BlobDomain) getAttributeInternal(IMAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for IMAGE using the alias name Image.
     * @param value value to set the IMAGE
     */
    public void setImage(BlobDomain value) {
        setAttributeInternal(IMAGE, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PartnerGroups.
     */
    public Row getPartnerGroups() {
        return (Row)getAttributeInternal(PARTNERGROUPS);
    }

    /**
     * Sets the master-detail link PartnerGroups between this object and <code>value</code>.
     */
    public void setPartnerGroups(Row value) {
        setAttributeInternal(PARTNERGROUPS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
