package com.vc.sasnmodel.views.sasn;

import com.vc.sasnmodel.entities.ServicesImpl;

import com.vc.sasnmodel.views.sasn.common.ServicesRow;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 20 22:33:09 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServicesRowImpl extends ViewRowImpl implements ServicesRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SerId {
            public Object get(ServicesRowImpl obj) {
                return obj.getSerId();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setSerId((Number)value);
            }
        }
        ,
        Title {
            public Object get(ServicesRowImpl obj) {
                return obj.getTitle();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setTitle((String)value);
            }
        }
        ,
        Content {
            public Object get(ServicesRowImpl obj) {
                return obj.getContent();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setContent((ClobDomain)value);
            }
        }
        ,
        CreateDate {
            public Object get(ServicesRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ServicesRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        ModifyDate {
            public Object get(ServicesRowImpl obj) {
                return obj.getModifyDate();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setModifyDate((Date)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(ServicesRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        Description {
            public Object get(ServicesRowImpl obj) {
                return obj.getDescription();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        PriorityOrder {
            public Object get(ServicesRowImpl obj) {
                return obj.getPriorityOrder();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setPriorityOrder((Number)value);
            }
        }
        ,
        SerIdChildOf {
            public Object get(ServicesRowImpl obj) {
                return obj.getSerIdChildOf();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setSerIdChildOf((Number)value);
            }
        }
        ,
        SerIdChildOfServices {
            public Object get(ServicesRowImpl obj) {
                return obj.getSerIdChildOfServices();
            }

            public void put(ServicesRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ServicesRowImpl object);

        public abstract void put(ServicesRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SERID = AttributesEnum.SerId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int CONTENT = AttributesEnum.Content.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int MODIFYDATE = AttributesEnum.ModifyDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int PRIORITYORDER = AttributesEnum.PriorityOrder.index();
    public static final int SERIDCHILDOF = AttributesEnum.SerIdChildOf.index();
    public static final int SERIDCHILDOFSERVICES = AttributesEnum.SerIdChildOfServices.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ServicesRowImpl() {
    }

    /**
     * Gets Services entity object.
     * @return the Services
     */
    public ServicesImpl getServices() {
        return (ServicesImpl)getEntity(0);
    }

    /**
     * Sets the master-detail link Services between this object and <code>value</code>.
     */
    public void setServices(oracle.jbo.Row value) {
        setAttributeInternal(SERIDCHILDOFSERVICES, value);
    }


    /**
     * Gets the attribute value for SER_ID using the alias name SerId.
     * @return the SER_ID
     */
    public Number getSerId() {
        return (Number) getAttributeInternal(SERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SER_ID using the alias name SerId.
     * @param value value to set the SER_ID
     */
    public void setSerId(Number value) {
        setAttributeInternal(SERID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for CONTENT using the alias name Content.
     * @return the CONTENT
     */
    public ClobDomain getContent() {
        return (ClobDomain) getAttributeInternal(CONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTENT using the alias name Content.
     * @param value value to set the CONTENT
     */
    public void setContent(ClobDomain value) {
        setAttributeInternal(CONTENT, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @return the MODIFY_DATE
     */
    public Date getModifyDate() {
        return (Date) getAttributeInternal(MODIFYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_DATE using the alias name ModifyDate.
     * @param value value to set the MODIFY_DATE
     */
    public void setModifyDate(Date value) {
        setAttributeInternal(MODIFYDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for PRIORITY_ORDER using the alias name PriorityOrder.
     * @return the PRIORITY_ORDER
     */
    public Number getPriorityOrder() {
        return (Number) getAttributeInternal(PRIORITYORDER);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_ORDER using the alias name PriorityOrder.
     * @param value value to set the PRIORITY_ORDER
     */
    public void setPriorityOrder(Number value) {
        setAttributeInternal(PRIORITYORDER, value);
    }

    /**
     * Gets the attribute value for SER_ID_CHILD_OF using the alias name SerIdChildOf.
     * @return the SER_ID_CHILD_OF
     */
    public Number getSerIdChildOf() {
        return (Number) getAttributeInternal(SERIDCHILDOF);
    }

    /**
     * Sets <code>value</code> as attribute value for SER_ID_CHILD_OF using the alias name SerIdChildOf.
     * @param value value to set the SER_ID_CHILD_OF
     */
    public void setSerIdChildOf(Number value) {
        setAttributeInternal(SERIDCHILDOF, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SerIdChildOfServices.
     */
    public RowIterator getSerIdChildOfServices() {
        return (RowIterator)getAttributeInternal(SERIDCHILDOFSERVICES);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
