package com.vc.sasnmodel.views.sasn.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 07 11:49:04 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContactInfosViewRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContactInfosViewRowClient() {
    }

    public String getAddress() {
        return (String)getAttribute("Address");
    }

    public void setAddress(String value) {
        setAttribute("Address", value);
    }

    public String getAttribute1() {
        return (String)getAttribute("Attribute1");
    }

    public void setAttribute1(String value) {
        setAttribute("Attribute1", value);
    }

    public String getAttribute2() {
        return (String)getAttribute("Attribute2");
    }

    public void setAttribute2(String value) {
        setAttribute("Attribute2", value);
    }

    public String getAttribute3() {
        return (String)getAttribute("Attribute3");
    }

    public void setAttribute3(String value) {
        setAttribute("Attribute3", value);
    }

    public String getAttribute4() {
        return (String)getAttribute("Attribute4");
    }

    public void setAttribute4(String value) {
        setAttribute("Attribute4", value);
    }

    public String getAttribute5() {
        return (String)getAttribute("Attribute5");
    }

    public void setAttribute5(String value) {
        setAttribute("Attribute5", value);
    }

    public Number getCinId() {
        return (Number)getAttribute("CinId");
    }

    public void setCinId(Number value) {
        setAttribute("CinId", value);
    }

    public String getCompanyName() {
        return (String)getAttribute("CompanyName");
    }

    public void setCompanyName(String value) {
        setAttribute("CompanyName", value);
    }

    public String getConfirmCode() {
        return (String)getAttribute("ConfirmCode");
    }

    public void setConfirmCode(String value) {
        setAttribute("ConfirmCode", value);
    }

    public String getContactName() {
        return (String)getAttribute("ContactName");
    }

    public void setContactName(String value) {
        setAttribute("ContactName", value);
    }

    public String getContent() {
        return (String)getAttribute("Content");
    }

    public void setContent(String value) {
        setAttribute("Content", value);
    }

    public String getCountry() {
        return (String)getAttribute("Country");
    }

    public void setCountry(String value) {
        setAttribute("Country", value);
    }

    public String getCreatedBy() {
        return (String)getAttribute("CreatedBy");
    }

    public void setCreatedBy(String value) {
        setAttribute("CreatedBy", value);
    }

    public Date getCreateDate() {
        return (Date)getAttribute("CreateDate");
    }

    public void setCreateDate(Date value) {
        setAttribute("CreateDate", value);
    }

    public String getEmailAddress() {
        return (String)getAttribute("EmailAddress");
    }

    public void setEmailAddress(String value) {
        setAttribute("EmailAddress", value);
    }

    public String getModifiedBy() {
        return (String)getAttribute("ModifiedBy");
    }

    public void setModifiedBy(String value) {
        setAttribute("ModifiedBy", value);
    }

    public Date getModifyDate() {
        return (Date)getAttribute("ModifyDate");
    }

    public void setModifyDate(Date value) {
        setAttribute("ModifyDate", value);
    }

    public String getPhoneNumber() {
        return (String)getAttribute("PhoneNumber");
    }

    public void setPhoneNumber(String value) {
        setAttribute("PhoneNumber", value);
    }
}
