package com.vc.sasnmodel.views.sasn.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 15 09:27:36 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentDownloadsRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DocumentDownloadsRowClient() {
    }

    public Number getDdoId() {
        return (Number)getAttribute("DdoId");
    }

    public void setDdoId(Number value) {
        setAttribute("DdoId", value);
    }

    public Number getDcaId() {
        return (Number)getAttribute("DcaId");
    }

    public void setDcaId(Number value) {
        setAttribute("DcaId", value);
    }

    public String getTitle() {
        return (String)getAttribute("Title");
    }

    public void setTitle(String value) {
        setAttribute("Title", value);
    }

    public String getShortContent() {
        return (String)getAttribute("ShortContent");
    }

    public void setShortContent(String value) {
        setAttribute("ShortContent", value);
    }

    public Date getPublicDate() {
        return (Date)getAttribute("PublicDate");
    }

    public void setPublicDate(Date value) {
        setAttribute("PublicDate", value);
    }

    public String getDownloadLink() {
        return (String)getAttribute("DownloadLink");
    }

    public void setDownloadLink(String value) {
        setAttribute("DownloadLink", value);
    }

    public BlobDomain getDownloadData() {
        return (BlobDomain)getAttribute("DownloadData");
    }

    public void setDownloadData(BlobDomain value) {
        setAttribute("DownloadData", value);
    }

    public Number getDataSize() {
        return (Number)getAttribute("DataSize");
    }

    public void setDataSize(Number value) {
        setAttribute("DataSize", value);
    }

    public Number getDownloadCount() {
        return (Number)getAttribute("DownloadCount");
    }

    public void setDownloadCount(Number value) {
        setAttribute("DownloadCount", value);
    }

    public Number getPriorityOrder() {
        return (Number)getAttribute("PriorityOrder");
    }

    public void setPriorityOrder(Number value) {
        setAttribute("PriorityOrder", value);
    }

    public String getFileName() {
        return (String)getAttribute("FileName");
    }

    public void setFileName(String value) {
        setAttribute("FileName", value);
    }

    public String getFileType() {
        return (String)getAttribute("FileType");
    }

    public void setFileType(String value) {
        setAttribute("FileType", value);
    }
}
