package com.vc.sasnmodel.views.sasn.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 14 10:24:49 ICT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GuestQuestionsRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GuestQuestionsRowClient() {
    }

    public Number getGquId() {
        return (Number)getAttribute("GquId");
    }

    public void setGquId(Number value) {
        setAttribute("GquId", value);
    }

    public String getTitle() {
        return (String)getAttribute("Title");
    }

    public void setTitle(String value) {
        setAttribute("Title", value);
    }

    public String getContent() {
        return (String)getAttribute("Content");
    }

    public void setContent(String value) {
        setAttribute("Content", value);
    }

    public Date getQuestionDate() {
        return (Date)getAttribute("QuestionDate");
    }

    public void setQuestionDate(Date value) {
        setAttribute("QuestionDate", value);
    }

    public String getGuestEmail() {
        return (String)getAttribute("GuestEmail");
    }

    public void setGuestEmail(String value) {
        setAttribute("GuestEmail", value);
    }

    public String getGuestTelephone() {
        return (String)getAttribute("GuestTelephone");
    }

    public void setGuestTelephone(String value) {
        setAttribute("GuestTelephone", value);
    }

    public Number getAgrId() {
        return (Number)getAttribute("AgrId");
    }

    public void setAgrId(Number value) {
        setAttribute("AgrId", value);
    }

    public String getAnswerMail() {
        return (String)getAttribute("AnswerMail");
    }

    public void setAnswerMail(String value) {
        setAttribute("AnswerMail", value);
    }

    public String getAnswerFlag() {
        return (String)getAttribute("AnswerFlag");
    }

    public void setAnswerFlag(String value) {
        setAttribute("AnswerFlag", value);
    }
}
