package com.perp.sasutilsmodel.entities;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 09 11:50:48 ICT 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerpSasUtilsAppModuleImpl extends ApplicationModuleImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public PerpSasUtilsAppModuleImpl() {
  }

  /**
   * Container's getter for Sasu001SendEmailLists.
   * @return Sasu001SendEmailLists
   */
  public ViewObjectImpl getSasu001SendEmailLists() {
    return (ViewObjectImpl)findViewObject("Sasu001SendEmailLists");
  }
}
